### PR TITLE
Fix bug with rporv

### LINKED ISSUE #962: rd_grav_survey_assert_RPORV has infinite loop if no init_porv > 0
The problem is that it will try to check 100 random non-zero points, but there may be fewer than 100 non-zero points in which case it is just an infinite loop: https://github.com/equinor/resdata/blob/c76fecd7e9e909c509e94547cb37206901d83cfb/lib/resdata/rd_grav.cpp#L376

### PR DESCRIPTION
**Pull request by eivindjahren**
**Issue**
Resolves #962

### CODE REVIEW

**Review by berland — CHANGES_REQUESTED** [review]
This is no duplicate 👀

File: lib/include/resdata/rd_kw_magic.hpp [hunk 1]
```diff
@@ -17,7 +17,6 @@ extern "C" {
 /*****************************************************************/
 
 #define PORO_KW "PORO"
-#define PORV_KW "PORV"
```
Comment (berland) [inline lib/include/resdata/rd_kw_magic.hpp:20]: This is no duplicate..
